### PR TITLE
Fix bugs related to sidebar

### LINKED ISSUE #117: Bug with Appointment Observable List.
Bug is produced when the find command is used first and a command is used on a filtered list. All other appointments on the list will be removed.

### PR DESCRIPTION
**Pull request by nikele2001**
Adding appointments to clients does not preserve chronological ordering of appointments in sidebar unless user restarts the application. This makes it cumbersome for the user to obtain a list of pending appointments sorted chronologically.

Let's:
- preserve the chronological ordering of appointments in the appointment list at all times

Fixes #117

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -21,3 +21,4 @@ src/test/data/sandbox/
 # MacOS custom attributes files created by Finder
 .DS_Store
 docs/_site/
+.vscode/settings.json
```
Comment (nikele2001) [inline .gitignore:24]: Added .gitignore for VS code compatibilities

File: src/main/java/seedu/address/storage/JsonAdaptedAppointment.java [hunk 2]
```diff
@@ -25,13 +25,6 @@ public JsonAdaptedAppointment(String appointment) {
         this.appointment = appointment;
     }
 
-    /**
-     * Converts a given {@code Appointment} into this class for Jackson use.
-     */
-    public JsonAdaptedAppointment(Appointment source) {
-        appointment = source.toString();
-    }
```
Comment (nikele2001) [inline src/main/java/seedu/address/storage/JsonAdaptedAppointment.java:33]: Deleted this constructor method as it is never used.
