### PR TITLE
Fix invalid day bug

### LINKED ISSUE #241: Adding invalid date causes a bug
31 feb appointment is allowed to be stored and will be stored as the earliest possible date before eg.29feb on leap year and 28 feb for non-leap year.

Works on other months with less than 31 days. While parser does not allow more than 31 days, it allows to add 31th of the month for the months that do not have 31

### PR DESCRIPTION
**Pull request by AlyssaPng**
fix #241

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -185,14 +186,35 @@ public static Appointment parseAppointment(String appointmentName, String appoin
...
 
         return new Appointment(trimmedAppointmentName, appointmentDate);
     }
 
+    /**
+     * Parses a {@code String date} into a {@code LocalDateTime}.
+     *
+     * @throws ParseException if the given {@code date} is invalid.
+     */
+    public static LocalDateTime parseValidAppointmentDate(String appointmentDateString) throws ParseException {
```
Comment (sopa301) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:202]: Perhaps it would be better to leave it as `parseAppointmentDate`, because this method still throws a `ParseException`. It can't be valid if it still has a risk of throwing an error, right?

Or, maybe `parseAppointmentDateTime` would be better because it returns a LocalDateTime.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -206,13 +228,16 @@ public static LocalDate parseDate(String date) throws ParseException {
         String dateValidation = "\\d{2}-\\d{2}-\\d{4}";
```
Comment (sopa301) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:228]: This is a bit arcane to the clueless. Since there is a `Date` regex in the `Appointment` class, perhaps we could move this there? We'll have to rename the regex already there since it's actually a `DateTime` regex.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 3]
```diff
@@ -206,13 +228,16 @@ public static LocalDate parseDate(String date) throws ParseException {
...
         DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
```
Comment (sopa301) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:229]: Same for this DateTimeFormatter and in the `parseValidAppointmentDate()`, with another existing regex in the `Appointment` class. (Unhinged) Maybe we could even make a static Date class to hold all this functionality?

**Review by sopa301 — COMMENTED** [review]
Thanks for the good effort. I think the SLAP is done quite well, though the naming could be a bit more intuitive. Some other things I noticed:
- Javadoc for parseAppointment (aptName and aptDate are outdated).
- (Nitpick) The validation for the `Date` and date part of `DateTime` is duplicated. Perhaps we could extract it into a method?
- The `Appointment` class method seems to have a few parse methods that may be better located here.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 3 above)
Comment (sopa301) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java:229]: @Kb-Tay I'd like your input on these too, since you're the original author of this code.

**Comment by sopa301** [comment]
@Kb-Tay I'd like your input on these too, since you're the original author of this code

File: src/test/java/seedu/address/logic/parser/ParserUtilTest.java [hunk 4]
```diff
@@ -314,4 +316,36 @@ public void validateFinancialPlans_missingInputs_throwsParseException() {
...
+        } catch (ParseException e) {
+            fail();
+        }
+    }
+
+    @Test
+    void parseValidAppointmentDate_invalidDate_shouldThrowParseException() {
+        String invalidDateString = "31-02-2022 14:30";
+        assertThrows(ParseException.class, () -> ParserUtil.parseValidAppointmentDate(invalidDateString));
+    }
```
Comment (Kb-Tay) [inline src/test/java/seedu/address/logic/parser/ParserUtilTest.java:350]: Can consider inputs such as 29th Feb for leap year, 29th Feb for non leap year, 31st for month like April instead of Febuary to make testing more comprehensive

**Review by Kb-Tay — COMMENTED** [review]
Overall, the code implemention is good in readability and has appropiate SLAP. However, can make some edits to prevent repetition of code. Can also consider including more test cases to ensure its comprehensiveness

**Review by sopa301 — APPROVED** [review]
LGTM
